name: Demo 05 - Pull Request

on:
  pull_request:
    branches: 
      - main
  
jobs:
  build-test-branch:
    name: "Build and Test Of PR"
    runs-on: ubuntu-20.04   # Changed from ubuntu-latest to ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      
      - name: Install dependencies
        run: dotnet restore "${{ github.workspace }}/mywebapp/mywebapp.sln"
      
      - name: Build
        run: dotnet build "${{ github.workspace }}/mywebapp/mywebapp.sln" --configuration Release --no-restore
      
      - name: Test
        run: |
          dotnet test "${{ github.workspace }}/mywebapp/mywebapp.sln" --no-restore --verbosity normal --logger "trx;LogFileName=test-results.trx"
      
      - name: Publish
        run: |
          dotnet publish "${{ github.workspace }}/mywebapp/src/mywebapp.csproj" -c Release -o mywebapp
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mywebappbuildartifacts
          path: mywebapp/**
          if-no-files-found: error
          retention-days: 90
