name: Build, Test, and Deploy to Network Share

on:
   pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest  # We use Windows so UNC paths can be handled easily

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Restore
        run: dotnet restore mywebapp/mywebapp.sln

      - name: Build
        run: dotnet build mywebapp/mywebapp.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test mywebapp/mywebapp.sln --no-restore --logger "trx;LogFileName=test-results.trx"

      - name: Publish
        run: dotnet publish mywebapp/src/mywebapp.csproj -c Release -o published

      - name: Deploy to Network Share
        shell: pwsh
        run: |
          Write-Host "Deploying application to a Windows share..."
          
          # The path to your published output.
          $source = "${{ github.workspace }}\published"  # For example: D:\a\YourRepo\published
          
          # The UNC path of your network share where you want to deploy.
          $destination = "\\SHASHANK\Users\spaka\OneDrive\Desktop\deploy"
          
          # 1. Map the network share using 'net use' with your stored secrets.
          net use $destination /user:${{ secrets.SHARE_USERNAME }} ${{ secrets.SHARE_PASSWORD }} | Out-Null
          
          # 2. Copy the published files recursively to the share.
          Copy-Item -Path "$source\*" -Destination $destination -Recurse -Force
          
          # 3. (Optional) Disconnect from the share.
          net use $destination /delete | Out-Null
          
          Write-Host "Deployment complete."
